#!/usr/bin/env python3
"""
Analyse a campaign CSV and emit the exact quantities the manuscript reports.

For every metric and arrival rate, against a named reference arm:
  mean, SD, 95% CI (t, df = n-1), Welch t, Welch-Satterthwaite df, exact p,
  Holm-Bonferroni adjusted p within the metric family, Hedges' g from the
  non-pooled SD with its 95% CI, and Shapiro-Wilk W and p per sample.

Also reports:
  admission table (offered / served / dropped / served fraction / saturation)
  minimum detectable effect at 80% power
  Spearman correlation of each metric against trial index (independence)

Every table in the paper should be generated by this script and by nothing
else. If a number appears in the manuscript that this script does not print,
that number has no provenance.
"""
import argparse, sys
from pathlib import Path
import numpy as np
import pandas as pd
from scipy import stats

METRICS = [
    ("mean_throughput_proofs_s", "Throughput (proofs/s)", "higher"),
    ("mean_latency_ms", "Mean latency (ms)", "lower"),
    ("median_latency_ms", "Median latency (ms)", "lower"),
    ("p95_latency_ms", "95th percentile latency (ms)", "lower"),
    ("p99_latency_ms", "99th percentile latency (ms)", "lower"),
    ("coeff_variation", "Latency coefficient of variation", "lower"),
    ("mean_cpu_pct", "Mean CPU utilization (%)", "lower"),
    ("peak_cpu_pct", "Peak CPU utilization (%)", "lower"),
    ("mean_memory_gb", "Mean memory (GB)", "lower"),
    ("mean_buffer_occupancy_pct", "Mean buffer occupancy (%)", "lower"),
    ("mean_batch_size", "Mean batch size (proofs)", "n/a"),
]
ADMISSION_CRITERION = 0.99


def hedges_g_nonpooled(a, b):
    """Hedges' g using the non-pooled SD, small-sample corrected at Welch df."""
    na, nb = len(a), len(b)
    va, vb = a.var(ddof=1), b.var(ddof=1)
    sd = np.sqrt((va + vb) / 2.0)
    if sd == 0:
        return float("nan"), (float("nan"), float("nan"))
    d = (a.mean() - b.mean()) / sd
    df = (va / na + vb / nb) ** 2 / ((va / na) ** 2 / (na - 1) +
                                     (vb / nb) ** 2 / (nb - 1))
    J = 1.0 - 3.0 / (4.0 * df - 1.0)
    g = J * d
    se = np.sqrt((na + nb) / (na * nb) + g ** 2 / (2 * (na + nb - 2)))
    return g, (g - 1.96 * se, g + 1.96 * se)


def holm(pvals):
    p = np.asarray(pvals, float)
    order = np.argsort(p)
    m = len(p)
    adj = np.empty(m)
    running = 0.0
    for rank, idx in enumerate(order):
        val = (m - rank) * p[idx]
        running = max(running, val)
        adj[idx] = min(running, 1.0)
    return adj


def ci(x):
    n = len(x)
    h = stats.t.ppf(0.975, n - 1) * x.std(ddof=1) / np.sqrt(n)
    return x.mean() - h, x.mean() + h


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--treatment", default="adaptive")
    ap.add_argument("--reference", default="fixed")
    ap.add_argument("--out", default="data/processed")
    args = ap.parse_args()

    df = pd.read_csv(args.csv)
    outdir = Path(args.out); outdir.mkdir(parents=True, exist_ok=True)

    # ---------------- admission ----------------
    print("\n=== ADMISSION AND SATURATION " + "=" * 46)
    adm = (df.groupby(["scheduler", "arrival_rate_txs"])
             .agg(served=("served_rate_proofs_s", "mean"),
                  served_sd=("served_rate_proofs_s", "std"),
                  frac=("served_fraction", "mean"),
                  drop=("drop_fraction", "mean"),
                  backlog=("final_tx_queue", "mean"),
                  n=("trial_id", "count")).reset_index())
    adm["below_saturation"] = np.where(adm["frac"] >= ADMISSION_CRITERION,
                                       "Yes", "No")
    adm["shortfall_pct"] = (1 - adm["frac"]) * 100
    print(adm.to_string(index=False,
                        float_format=lambda v: f"{v:.4g}"))
    adm.to_csv(outdir / "admission_table.csv", index=False)

    for s in sorted(adm.scheduler.unique()):
        sub = adm[(adm.scheduler == s) & (adm.below_saturation == "Yes")]
        knee = sub.arrival_rate_txs.max() if len(sub) else float("nan")
        print(f"  saturation point, {s}: highest rate meeting the "
              f"{ADMISSION_CRITERION:.0%} criterion = {knee:g} tx/s")

    # ---------------- power ----------------
    n = int(df.groupby(["scheduler", "arrival_rate_txs"]).size().min())
    mde = (stats.norm.ppf(0.975) + stats.norm.ppf(0.80)) * np.sqrt(2.0 / n)
    print(f"\nminimum detectable standardized effect "
          f"(n={n}/arm, alpha=0.05 two-sided, power=0.80): {mde:.3f}")

    # ---------------- independence ----------------
    print("\n=== TRIAL INDEPENDENCE (Spearman vs trial index) " + "=" * 26)
    rows = []
    for (s, r), grp in df.groupby(["scheduler", "arrival_rate_txs"]):
        for m, _, _ in METRICS:
            if grp[m].notna().sum() < 5 or grp[m].nunique() < 3:
                continue
            rho, p = stats.spearmanr(grp["trial_id"], grp[m])
            rows.append({"scheduler": s, "rate": r, "metric": m,
                         "rho": rho, "p": p})
    ind = pd.DataFrame(rows)
    if len(ind):
        ind["p_holm"] = holm(ind["p"].values)
        print(f"  {len(ind)} metric-by-configuration pairs; "
              f"|rho| in [{ind.rho.abs().min():.3f}, {ind.rho.abs().max():.3f}]; "
              f"smallest raw p = {ind.p.min():.3f}; "
              f"smallest Holm-adjusted p = {ind.p_holm.min():.3f}")
        ind.to_csv(outdir / "independence.csv", index=False)

    # ---------------- comparisons ----------------
    print(f"\n=== {args.treatment.upper()} vs {args.reference.upper()} "
          + "=" * 40)
    results = []
    for metric, label, _ in METRICS:
        fam = []
        for rate in sorted(df.arrival_rate_txs.unique()):
            a = df[(df.scheduler == args.treatment) &
                   (df.arrival_rate_txs == rate)][metric].dropna().values
            b = df[(df.scheduler == args.reference) &
                   (df.arrival_rate_txs == rate)][metric].dropna().values
            if len(a) < 3 or len(b) < 3:
                continue
            t, p = stats.ttest_ind(a, b, equal_var=False)
            va, vb, na, nb = a.var(ddof=1), b.var(ddof=1), len(a), len(b)
            wdf = (va/na + vb/nb) ** 2 / ((va/na) ** 2 / (na-1) +
                                          (vb/nb) ** 2 / (nb-1))
            g, (glo, ghi) = hedges_g_nonpooled(a, b)
            sw_a = stats.shapiro(a) if na >= 3 else (np.nan, np.nan)
            sw_b = stats.shapiro(b) if nb >= 3 else (np.nan, np.nan)
            fam.append(dict(metric=metric, label=label, rate=rate,
                            a_mean=a.mean(), a_sd=a.std(ddof=1),
                            a_lo=ci(a)[0], a_hi=ci(a)[1],
                            b_mean=b.mean(), b_sd=b.std(ddof=1),
                            b_lo=ci(b)[0], b_hi=ci(b)[1],
                            delta_pct=100*(a.mean()-b.mean())/b.mean()
                            if b.mean() else np.nan,
                            t=t, df=wdf, p_raw=p, g=g, g_lo=glo, g_hi=ghi,
                            shapiro_p_treatment=sw_a[1],
                            shapiro_p_reference=sw_b[1]))
        if not fam:
            continue
        fam_df = pd.DataFrame(fam)
        fam_df["p_holm"] = holm(fam_df["p_raw"].values)   # within metric family
        results.append(fam_df)
        print(f"\n{label}")
        for _, r in fam_df.iterrows():
            print(f"  {r['rate']:>7.0f} tx/s  "
                  f"{r.a_mean:10.3f} ({r.a_sd:7.3f}) [{r.a_lo:9.3f},{r.a_hi:9.3f}]  vs  "
                  f"{r.b_mean:10.3f} ({r.b_sd:7.3f})  "
                  f"D={r.delta_pct:+7.2f}%  t={r.t:9.3f} (df={r.df:5.1f})  "
                  f"p={r.p_holm:.3e}  g={r.g:+7.2f} [{r.g_lo:+.2f},{r.g_hi:+.2f}]")

    if results:
        allr = pd.concat(results, ignore_index=True)
        allr.to_csv(outdir / "comparisons.csv", index=False)
        print(f"\nwrote {outdir}/comparisons.csv, admission_table.csv, "
              f"independence.csv")


if __name__ == "__main__":
    main()
